(source_file (package_header 


(identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) 
(import_list (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) 
(import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier)))
x (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier)))) (import_list (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier))) (import_header (identifier (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier) (simple_identifier)))) 





(class_declaration 
  (modifiers (annotation (user_type (type_identifier)))
             (annotation (constructor_invocation (user_type (type_identifier))
             (value_arguments (value_argument (string_literal (string_content)))))))
             (type_identifier)
             (primary_constructor (class_parameter (modifiers (visibility_modifier)) (binding_pattern_kind) (simple_identifier) (user_type (type_identifier))))
             (class_body (function_declaration (modifiers (annotation (user_type (type_identifier)))) (simple_identifier) (function_value_parameters) (user_type (type_identifier) (type_arguments (type_projection))) (function_body (statements (jump_expression (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments))))))))))) (function_declaration (modifiers (annotation (constructor_invocation (user_type (type_identifier)) (value_arguments (value_argument (string_literal (string_content))))))) (simple_identifier) (function_value_parameters (parameter_modifiers (annotation (user_type (type_identifier)))) (parameter (simple_identifier) (user_type (type_identifier)))) (user_type (type_identifier) (type_arguments (type_projection))) (function_body (statements (jump_expression (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (simple_identifier))))))))))))) (function_declaration (modifiers (annotation (user_type (type_identifier)))) (simple_identifier) (function_value_parameters (parameter_modifiers (annotation (user_type (type_identifier)))) (parameter (simple_identifier) (user_type (type_identifier)))) (user_type (type_identifier) (type_arguments (type_projection))) (function_body (statements (jump_expression (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (simple_identifier))))))))))))) (function_declaration (modifiers (annotation (constructor_invocation (user_type (type_identifier)) (value_arguments (value_argument (simple_identifier) (collection_literal (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))))) (value_argument (simple_identifier) (collection_literal (string_literal (string_content)))))))) (simple_identifier) (function_value_parameters (parameter_modifiers (annotation (user_type (type_identifier)))) (parameter (simple_identifier) (user_type (type_identifier)))) (user_type (type_identifier) (type_arguments (type_projection))) (function_body (statements (jump_expression (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (simple_identifier))))))))))))))))





(source_file (class_declaration (type_identifier) (primary_constructor (class_parameter (modifiers (visibility_modifier)) (binding_pattern_kind) (simple_identifier) (user_type (type_identifier)))) (class_body (function_declaration (modifiers (annotation (constructor_invocation (user_type (type_identifier)) (value_arguments (value_argument (simple_identifier) (collection_literal (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))))) (value_argument (simple_identifier) (collection_literal (string_literal (string_content)))))))) (simple_identifier) (function_value_parameters


(parameter_modifiers 
(annotation (user_type (type_identifier)))) (parameter (simple_identifier) (user_type (type_identifier)))) (user_type (type_identifier) (type_arguments (type_projection))) (function_body (statements (jump_expression (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (call_expression (navigation_expression (simple_identifier) (navigation_suffix (simple_identifier))) (call_suffix (value_arguments (value_argument (simple_identifier))))))))))))))))